version: "3.8"

services:
  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - REDIS_URI=redis://redis:6379
      - WHATSAPP_SECRET:${WHATSAPP_SECRET}
    depends_on:
      - redis
    volumes:
      - .:/app # Map the current directory to /app in the container
      - /app/node_modules # Prevent the node_modules in the container from being overwritten

  redis:
    image: redis
    ports:
      - "6379:6379"
